create_parcel_kb = {
    # "DefaultHeight": True,
    # "CustomDefaultHeight": 70,
    # "BgColor": "#4d79ff",
    "Type": "keyboard",
    # "InputFieldState": "minimized",
    "Buttons": [
        {
            "Columns": 1,
            "Rows": 1,
            "BgColor": "#e6f5ff",
            # "BgLoop": True,
            "ActionType": "reply",
            "ActionBody": "XS",
            "ReplyType": "message",
            "TextSize": "large",
            "Text": "XS",
        },
        {
            "Columns": 1,
            "Rows": 1,
            "BgColor": "#e6f5ff",
            # "BgLoop": True,
            "ActionType": "reply",
            "ActionBody": "S",
            "ReplyType": "message",
            "TextSize": "large",
            "Text": "S",
        },
        {
            "Columns": 2,
            "Rows": 1,
            "BgColor": "#e6f5ff",
            # "BgLoop": True,
            "ActionType": "reply",
            "ActionBody": "M",
            "ReplyType": "message",
            "TextSize": "large",
            "Text": "M",
        },
        {
            "Columns": 2,
            "Rows": 1,
            "BgColor": "#e6f5ff",
            # "BgLoop": True,
            "ActionType": "reply",
            "ActionBody": "XL",
            "ReplyType": "message",
            "TextSize": "large",
            "Text": "XL",
        },
        {
            "Columns": 6,
            "Rows": 1,
            "BgColor": "#e6f5ff",
            # "BgLoop": True,
            "ActionType": "reply",
            "ActionBody": "main_menu",
            "ReplyType": "message",
            "TextSize": "large",
            "Text": "До головного меню",
        }

    ]
}
